import 'dart:developer' as developer;
import 'package:dartz/dartz.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../core/error/exceptions.dart';
import '../../../core/error/failures.dart';
import '../../../core/network/network_info.dart';
import '../../../core/services/vercel_notification_service.dart';
import '../../domain/entities/notification.dart';
import '../../domain/repositories/notification_repository.dart';
import '../../domain/repositories/user_repository.dart';
import '../datasources/notifications/notification_remote_datasource.dart';
import '../models/notification_model.dart';
import '../services/push_notification_service.dart';

class NotificationRepositoryImpl implements NotificationRepository {
  final NotificationRemoteDataSource remoteDataSource;
  final UserRepository userRepository;
  final NetworkInfo networkInfo;
  final PushNotificationService pushNotificationService;

  NotificationRepositoryImpl({
    required this.remoteDataSource,
    required this.userRepository,
    required this.networkInfo,
    required this.pushNotificationService,
  });

  @override
  Future<Either<Failure, Notification>> sendNotification({
    required String title,
    required String message,
    required String type,
    required String recipientEmail,
    String? taskId,
    Map<String, dynamic>? data,
    String? actionUrl,
  }) async {
    try {
      if (await networkInfo.isConnected) {
        final notification = NotificationModel(
          notificationId: '', // Will be generated by Firestore
          title: title,
          message: message,
          type: type,
          recipientEmail: recipientEmail,
          taskId: taskId,
          data: data,
          createdAt: DateTime.now(),
          isRead: false,
          actionUrl: actionUrl,
        );

        final createdNotification = await remoteDataSource.createNotification(
          notification,
        );

        // Individual notifications don't trigger push notifications
        // Push notifications are handled at the sendNotificationToMultiple level
        // to avoid sending duplicates for each recipient

        return Right(createdNotification.toEntity());
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(ServerFailure(message: 'Failed to send notification: $e'));
    }
  }

  @override
  Future<Either<Failure, List<Notification>>> sendNotificationToMultiple({
    required String title,
    required String message,
    required String type,
    required List<String> recipientEmails,
    String? taskId,
    Map<String, dynamic>? data,
    String? actionUrl,
  }) async {
    try {
      if (await networkInfo.isConnected) {
        final notifications = <Notification>[];

        // Send notifications to each recipient
        for (final email in recipientEmails) {
          final result = await sendNotification(
            title: title,
            message: message,
            type: type,
            recipientEmail: email,
            taskId: taskId,
            data: data,
            actionUrl: actionUrl,
          );

          result.fold(
            (failure) => throw Exception(failure.message),
            (notification) => notifications.add(notification),
          );
        }

        // Send push notification ONCE after all individual notifications are created
        // This ensures we don't send duplicate push notifications for each recipient
        if (type == 'new_task' && taskId != null && data != null) {
          await _sendPushNotificationForNewTask(
            taskId: taskId,
            title: title,
            message: message,
            data: data,
          );
        }

        return Right(notifications);
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } catch (e) {
      return Left(ServerFailure(message: 'Failed to send notifications: $e'));
    }
  }

  @override
  Future<Either<Failure, List<Notification>>>
  sendNotificationToManagersAndAdmins({
    required String title,
    required String message,
    required String type,
    String? taskId,
    String? taskCategory, // New parameter for category filtering
    Map<String, dynamic>? data,
    String? actionUrl,
  }) async {
    try {
      // Get all managers
      final managersResult = await userRepository.getManagers();

      return await managersResult.fold((failure) => Left(failure), (
        managers,
      ) async {
        // Filter managers by task category (if provided)
        List<dynamic> filteredManagers = managers;
        if (taskCategory != null) {
          filteredManagers = managers.where((manager) {
            // If manager has managedCategories, check if it includes the task category
            // If managedCategories is null or empty, manager handles all categories (backward compatibility)
            if (manager.managedCategories == null ||
                manager.managedCategories!.isEmpty) {
              return true; // Handle all categories
            }
            return manager.managedCategories!.contains(taskCategory);
          }).toList();
        }

        // Get all admins (admins always receive all notifications)
        final adminsResult = await userRepository.getUsersByRole(role: 'Admin');

        return await adminsResult.fold((failure) => Left(failure), (
          admins,
        ) async {
          // Combine filtered managers and all admins, remove duplicates
          final allRecipients = <String>{};
          for (final manager in filteredManagers) {
            allRecipients.add(manager.userEmail);
          }
          for (final admin in admins) {
            allRecipients.add(admin.userEmail);
          }

          // Send notifications
          final result = await sendNotificationToMultiple(
            title: title,
            message: message,
            type: type,
            recipientEmails: allRecipients.toList(),
            taskId: taskId,
            data: data,
            actionUrl: actionUrl,
          );

          // Push notification is already sent by sendNotificationToMultiple above
          // No need to call _sendPushNotificationForNewTask again here

          return result;
        });
      });
    } catch (e) {
      return Left(
        ServerFailure(
          message: 'Failed to send notifications to managers and admins: $e',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, List<Notification>>> getNotificationsForUser({
    required String userEmail,
    int? limit,
    String? lastNotificationId,
  }) async {
    try {
      if (await networkInfo.isConnected) {
        final notifications = await remoteDataSource.getNotificationsForUser(
          userEmail: userEmail,
          limit: limit,
          lastNotificationId: lastNotificationId,
        );
        return Right(notifications.map((n) => n.toEntity()).toList());
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(ServerFailure(message: 'Failed to get notifications: $e'));
    }
  }

  @override
  Future<Either<Failure, int>> getUnreadNotificationsCount(
    String userEmail,
  ) async {
    try {
      if (await networkInfo.isConnected) {
        final count = await remoteDataSource.getUnreadNotificationsCount(
          userEmail,
        );
        return Right(count);
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(
        ServerFailure(message: 'Failed to get unread notifications count: $e'),
      );
    }
  }

  @override
  Future<Either<Failure, Notification>> markAsRead(
    String notificationId,
  ) async {
    try {
      if (await networkInfo.isConnected) {
        final updatedNotification = await remoteDataSource.updateNotification(
          notificationId,
          {'isRead': true},
        );
        return Right(updatedNotification.toEntity());
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(
        ServerFailure(message: 'Failed to mark notification as read: $e'),
      );
    }
  }

  @override
  Future<Either<Failure, void>> markAllAsRead(String userEmail) async {
    try {
      if (await networkInfo.isConnected) {
        // Get all unread notifications for the user
        final notifications = await remoteDataSource.getNotificationsForUser(
          userEmail: userEmail,
        );

        // Update each unread notification
        for (final notification in notifications) {
          if (!notification.isRead) {
            await remoteDataSource.updateNotification(
              notification.notificationId,
              {'isRead': true},
            );
          }
        }

        return const Right(null);
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(
        ServerFailure(message: 'Failed to mark all notifications as read: $e'),
      );
    }
  }

  @override
  Future<Either<Failure, void>> deleteNotification(
    String notificationId,
  ) async {
    try {
      if (await networkInfo.isConnected) {
        await remoteDataSource.deleteNotification(notificationId);
        return const Right(null);
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(ServerFailure(message: 'Failed to delete notification: $e'));
    }
  }

  @override
  Future<Either<Failure, void>> deleteAllNotifications(String userEmail) async {
    try {
      if (await networkInfo.isConnected) {
        await remoteDataSource.deleteAllNotifications(userEmail);
        return const Right(null);
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(
        ServerFailure(message: 'Failed to delete all notifications: $e'),
      );
    }
  }

  @override
  Future<Either<Failure, void>> deleteNotificationsByTaskId(
    String taskId,
  ) async {
    try {
      if (await networkInfo.isConnected) {
        await remoteDataSource.deleteNotificationsByTaskId(taskId);
        return const Right(null);
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(
        ServerFailure(message: 'Failed to delete notifications by task ID: $e'),
      );
    }
  }

  @override
  Future<Either<Failure, Notification>> getNotificationById(
    String notificationId,
  ) async {
    try {
      if (await networkInfo.isConnected) {
        final notification = await remoteDataSource.getNotificationById(
          notificationId,
        );
        return Right(notification.toEntity());
      } else {
        return const Left(NetworkFailure(message: 'No internet connection'));
      }
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(ServerFailure(message: 'Failed to get notification: $e'));
    }
  }

  @override
  Stream<Either<Failure, List<Notification>>> getNotificationsStream(
    String userEmail,
  ) {
    try {
      return remoteDataSource
          .getNotificationsStream(userEmail)
          .map(
            (notifications) => Right<Failure, List<Notification>>(
              notifications.map((n) => n.toEntity()).toList(),
            ),
          );
    } catch (e) {
      return Stream.value(
        Left(ServerFailure(message: 'Failed to get notifications stream: $e')),
      );
    }
  }

  // Helper method to send push notifications for new tasks using TOKEN-BASED approach (PRODUCTION READY)
  Future<void> _sendPushNotificationForNewTask({
    required String taskId,
    required String title,
    required String message,
    required Map<String, dynamic> data,
  }) async {
    try {
      developer.log(
        '🔔 🚀 Starting TOKEN-BASED push notification for task: $taskId',
      );
      developer.log('🔔 Title: $title');
      developer.log('🔔 Message: $message');
      developer.log('🔔 Data: $data');

      final taskTitle =
          data['taskTitle'] as String? ?? title; // Use title as fallback
      final employeeName =
          data['employeeName'] as String? ?? 'Unknown Employee';
      final priority = data['priority'] as String? ?? 'Normal';
      final category = data['category'] as String? ?? 'General';

      developer.log('🔔 Extracted values:');
      developer.log('🔔 - taskTitle: $taskTitle');
      developer.log('🔔 - employeeName: $employeeName');
      developer.log('🔔 - priority: $priority');
      developer.log('🔔 - category: $category');

      // 🎯 PRIMARY APPROACH: TOKEN-BASED (PROVEN TO WORK)
      developer.log('🔔 🎯 Getting manager and admin FCM tokens...');
      final managerTokens = await _getManagerAndAdminTokens();

      if (managerTokens.isNotEmpty) {
        developer.log('🔔 Found ${managerTokens.length} manager/admin tokens');

        final vercelService = VercelNotificationService();
        final tokenResult = await vercelService.sendNotificationToManagers(
          managerTokens: managerTokens,
          taskId: taskId,
          taskTitle: taskTitle,
          employeeName: employeeName,
          priority: priority,
          category: category,
        );

        tokenResult.fold(
          (failure) => developer.log(
            '🔔 ❌ Token-based notification failed: ${failure.message}',
          ),
          (_) => developer.log(
            '🔔 ✅ Token-based notification sent to ${managerTokens.length} managers!',
          ),
        );
      } else {
        developer.log(
          '🔔 ⚠️ No manager/admin tokens found - falling back to topic-based approach',
        );

        // 🎯 FALLBACK APPROACH: TOPIC-BASED (for cases where tokens not available)
        final vercelService = VercelNotificationService();
        final topicResult = await vercelService.sendNewTaskNotification(
          taskId: taskId,
          taskTitle: taskTitle,
          employeeName: employeeName,
          priority: priority,
          category: category,
        );

        topicResult.fold(
          (failure) => developer.log(
            '🔔 ❌ Topic-based fallback failed: ${failure.message}',
          ),
          (_) => developer.log('🔔 ✅ Topic-based fallback sent successfully!'),
        );
      }

      developer.log(
        '🔔 🎉 Push notification process completed for task: $taskId',
      );
    } catch (e) {
      // Log error but don't fail the notification creation
      developer.log('🔔 ❌ Exception in push notification: $e');
    }
  }

  // Helper method to get FCM tokens for managers and admins
  Future<List<String>> _getManagerAndAdminTokens() async {
    try {
      final tokens = <String>[];

      developer.log(
        '🔔 🔍 DEBUG: Querying users collection for Manager/Admin roles...',
      );

      // Get all users with Manager or Admin role
      final userQuery = await FirebaseFirestore.instance
          .collection('users')
          .where('role', whereIn: ['Manager', 'Admin'])
          .get();

      developer.log(
        '🔔 🔍 DEBUG: Found ${userQuery.docs.length} users with Manager/Admin role',
      );

      for (final doc in userQuery.docs) {
        final userData = doc.data();
        developer.log('🔔 🔍 DEBUG: Processing user: ${doc.id}');
        developer.log('🔔 🔍 DEBUG: User data: $userData');

        final userTokens = userData['fcmTokens'] as List<dynamic>?;
        developer.log('🔔 🔍 DEBUG: FCM tokens for ${doc.id}: $userTokens');

        if (userTokens != null && userTokens.isNotEmpty) {
          // Add all valid tokens for this user
          for (final token in userTokens) {
            if (token is String && token.isNotEmpty) {
              tokens.add(token);
              developer.log(
                '🔔 🔍 DEBUG: Added token: ${token.substring(0, 20)}...',
              );
            }
          }
        } else {
          developer.log('🔔 🔍 DEBUG: No FCM tokens found for user ${doc.id}');
        }
      }

      developer.log(
        '🔔 🔍 DEBUG: FINAL RESULT - Retrieved ${tokens.length} FCM tokens from ${userQuery.docs.length} manager/admin users',
      );
      return tokens;
    } catch (e) {
      developer.log('🔔 ❌ Error getting manager/admin tokens: $e');
      return [];
    }
  }
}
