// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2QVByfdvSxSonEMfFZuYKoc8iEVVpK-4',
    appId: '1:737561395502:web:1c0a450e0fe82c737bbabf',
    messagingSenderId: '737561395502',
    projectId: 'complaints-712af',
    authDomain: 'complaints-712af.firebaseapp.com',
    storageBucket: 'complaints-712af.firebasestorage.app',
    measurementId: 'G-WCJDE57LXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZBBKj8r8nJhT057NiagWiyybXKEA8uA',
    appId: '1:737561395502:android:4d198d5dad24a4937bbabf',
    messagingSenderId: '737561395502',
    projectId: 'complaints-712af',
    storageBucket: 'complaints-712af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7pWGfF2s8cKgWA_mJ-OChUrq-4onCP9c',
    appId: '1:737561395502:ios:995fe6562ad879487bbabf',
    messagingSenderId: '737561395502',
    projectId: 'complaints-712af',
    storageBucket: 'complaints-712af.firebasestorage.app',
    iosBundleId: 'com.example.complaints',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7pWGfF2s8cKgWA_mJ-OChUrq-4onCP9c',
    appId: '1:737561395502:ios:995fe6562ad879487bbabf',
    messagingSenderId: '737561395502',
    projectId: 'complaints-712af',
    storageBucket: 'complaints-712af.firebasestorage.app',
    iosBundleId: 'com.example.complaints',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2QVByfdvSxSonEMfFZuYKoc8iEVVpK-4',
    appId: '1:737561395502:web:f09c85f58b8ce7ad7bbabf',
    messagingSenderId: '737561395502',
    projectId: 'complaints-712af',
    authDomain: 'complaints-712af.firebaseapp.com',
    storageBucket: 'complaints-712af.firebasestorage.app',
    measurementId: 'G-7Z31SYW1JD',
  );
}
